apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeastra.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubeastra.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubeastra.frontend.selectorLabels" . | nindent 4 }}
